name: Run tests

on:
  push:
    branches:
      - master
    paths:
      - "**/*.php"
  pull_request:

jobs:
  php-tests:
    runs-on: ubuntu-22.04
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      fail-fast: true
      matrix:
        php-version: [8.1, 8.2, 8.3]
        laravel-version: [10.*]

    name: PHP ${{ matrix.php-version }} | Laravel - ${{ matrix.laravel-version }}

    steps:
      - uses: actions/checkout@v4

      # see https://github.com/shivammathur/setup-php
      - name: Prepare PHP test environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-laravel-${{ matrix.laravel-version }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel-version }}" "orchestra/testbench:8.*" --no-interaction --no-update
          composer update --prefer-dist --no-interaction
          ./vendor/bin/testbench orchid:install

      - name: Running tests
        run: composer test
